export const weeklyData = [
  { date: "23 Jun", external: 280 },
  { date: "24 Jun", external: 450 },
  { date: "25 Jun", external: 230 },
  { date: "26 Jun", external: 380 },
  { date: "27 Jun", external: 150 },
  { date: "28 Jun", external: 390 },
  { date: "29 Jun", external: 320 },
];

export const monthlyData = [
  { date: "Week 1", external: 1200 },
  { date: "Week 2", external: 1850 },
  { date: "Week 3", external: 1470 },
  { date: "Week 4", external: 1980 },
];

export const yearlyData = [
  { date: "Jan", external: 5400 },
  { date: "Feb", external: 6200 },
  { date: "Mar", external: 7000 },
  { date: "Apr", external: 6800 },
  { date: "May", external: 7500 },
  { date: "Jun", external: 8100 },
  { date: "Jul", external: 8700 },
  { date: "Aug", external: 9100 },
  { date: "Sep", external: 8900 },
  { date: "Oct", external: 9400 },
  { date: "Nov", external: 9700 },
  { date: "Dec", external: 10200 },
];

export const pieData = [
  { name: "Real Estate", value: 50 },
  { name: "Life", value: 30 },
  { name: "Insurance", value: 20 },
];

export const pieCOLORS = ["#0088FE", "#00C49F", "#FFBB28"];

export const blogs = [
  {
    title: "The Future of Real Estate",
    category: "Real Estate",
    date: "2025-02-20",
  },
  {
    title: "Life Insurance Explained",
    category: "Insurance",
    date: "2025-02-18",
  },
  { title: "Home Buying Guide", category: "Real Estate", date: "2025-02-15" },
  { title: "Financial Security Tips", category: "Life", date: "2025-02-10" },
];

export const prompts = [
  // Real Estate
  "Suggest 5 creative blog topics related to real estate and property investment.",
  "Generate 5 trending blog ideas for home buyers and sellers in today's market.",
  "List 5 insightful topics about real estate market trends and predictions.",
  "Provide 5 expert tips on choosing the right real estate investment opportunities.",
  "Suggest 5 engaging blog ideas about the pros and cons of renting vs. buying a home.",

  // Insurance
  "Generate 5 informative blog topics about the importance of life insurance policies.",
  "List 5 blog ideas on common misconceptions about home insurance.",
  "Suggest 5 must-know tips for choosing the best health insurance plan.",
  "Provide 5 engaging topics about how auto insurance rates are determined.",
  "Generate 5 creative blog ideas about the benefits of business insurance for entrepreneurs.",

  // Life
  "List 5 thought-provoking blog ideas about personal growth and self-improvement.",
  "Suggest 5 blog topics on how to maintain work-life balance in a fast-paced world.",
  "Provide 5 insightful ideas on overcoming life challenges and setbacks.",
  "Generate 5 blog post ideas about the benefits of daily mindfulness and meditation.",
  "List 5 engaging topics about breaking bad habits and building positive ones.",

  // Relationships
  "Suggest 5 blog topics on building strong and healthy romantic relationships.",
  "Generate 5 engaging blog post ideas about effective communication in relationships.",
  "List 5 insightful topics about navigating long-distance relationships successfully.",
  "Provide 5 blog ideas on resolving conflicts and strengthening emotional bonds.",
  "Suggest 5 creative topics about dating tips and modern relationship challenges.",

  // Managing Wealth
  "Generate 5 blog ideas about smart financial habits for long-term wealth building.",
  "List 5 insightful blog topics about investment strategies for beginners.",
  "Provide 5 engaging ideas on budgeting and saving money effectively.",
  "Suggest 5 blog topics about passive income opportunities for financial freedom.",
  "Generate 5 informative posts about the importance of retirement planning early.",

  // More Real Estate Topics
  "List 5 unique blog ideas about flipping houses for profit.",
  "Provide 5 tips on how to negotiate the best real estate deals.",
  "Suggest 5 engaging topics about how location impacts property value.",
  "Generate 5 creative blog topics about eco-friendly homes and sustainable living.",
  "List 5 insightful topics about the impact of inflation on the housing market.",

  // More Insurance Topics
  "Provide 5 blog ideas about understanding different types of life insurance policies.",
  "List 5 engaging topics about why renters should consider insurance.",
  "Generate 5 blog post ideas about the role of insurance in disaster recovery.",
  "Suggest 5 creative blog topics about car insurance claims and common mistakes to avoid.",
  "Provide 5 insightful blog ideas about choosing travel insurance for international trips.",

  // More Life Topics
  "List 5 unique blog topics about morning routines for success.",
  "Generate 5 blog ideas on how to develop a positive mindset.",
  "Provide 5 engaging topics about handling stress and anxiety in daily life.",
  "Suggest 5 insightful blog ideas about the impact of gratitude on happiness.",
  "List 5 creative blog topics about time management hacks for busy professionals.",

  // More Relationship Topics
  "Generate 5 blog ideas about rebuilding trust after betrayal.",
  "Provide 5 engaging topics about how to keep the spark alive in long-term relationships.",
  "List 5 insightful blog ideas about understanding love languages in relationships.",
  "Suggest 5 blog post ideas on setting healthy boundaries in friendships and dating.",
  "Generate 5 creative blog topics about navigating breakups and moving forward.",

  // More Wealth Management Topics
  "List 5 unique blog topics about tax-saving strategies for individuals and businesses.",
  "Provide 5 engaging ideas on the importance of financial literacy in today's world.",
  "Suggest 5 blog topics about real estate investment vs. stock market investment.",
  "Generate 5 insightful blog ideas about building multiple income streams.",
  "List 5 creative blog topics about how to retire early with smart financial planning.",

  // More Real Estate Insights
  "Provide 5 engaging blog ideas about smart home technology and its impact on real estate.",
  "List 5 unique topics about the future of real estate in the digital age.",
  "Generate 5 blog post ideas about investing in vacation rental properties.",
  "Suggest 5 insightful topics about understanding mortgage rates and home loans.",
  "Provide 5 creative blog ideas about real estate scams and how to avoid them.",

  // More Insurance Insights
  "List 5 engaging blog topics about how to lower your insurance premiums.",
  "Generate 5 blog post ideas about comparing different health insurance providers.",
  "Provide 5 unique blog topics about cyber insurance and its importance in the digital age.",
  "Suggest 5 insightful blog ideas about the impact of AI on the insurance industry.",
  "List 5 creative blog topics about pet insurance and why it's worth considering.",

  // More Life Tips
  "Generate 5 blog ideas about how to stay productive while working from home.",
  "Provide 5 engaging topics about overcoming imposter syndrome.",
  "List 5 insightful blog ideas about the importance of lifelong learning.",
  "Suggest 5 blog post ideas about travel experiences that can change your life.",
  "Generate 5 creative blog topics about ways to boost self-confidence.",

  // More Relationship Advice
  "List 5 unique blog topics about parenting and raising emotionally intelligent kids.",
  "Provide 5 engaging ideas on how to manage finances as a couple.",
  "Suggest 5 blog topics about dealing with toxic relationships and red flags to watch for.",
  "Generate 5 insightful blog ideas about relationship goals vs. unrealistic expectations.",
  "List 5 creative blog topics about how to maintain friendships as an adult.",

  // More Wealth Management Advice
  "Provide 5 blog ideas about how to teach kids about money and investing.",
  "List 5 engaging topics about financial mistakes to avoid in your 20s and 30s.",
  "Generate 5 blog post ideas about budgeting for big life events like weddings and buying a home.",
  "Suggest 5 insightful blog topics about cryptocurrency and its role in wealth management.",
  "Provide 5 creative blog ideas about minimalist living and financial freedom.",
];

export const fakeBlogs = [
  {
    _id: "1",
    title: "How to Start a Tech Business",
    description: "A guide to launching your startup...",
    author: "John Doe",
    category: "Business",
    date: "2024-02-19",
    isFeatured: false,
  },
  {
    _id: "2",
    title: "Understanding AI in 2024",
    description: "Exploring the impact of AI...",
    author: "Jane Smith",
    category: "Technology",
    date: "2024-02-18",
    isFeatured: true,
  },
  {
    _id: "3",
    title: "Web Development Trends",
    description: "The latest trends in web development...",
    author: "Mike Johnson",
    category: "Web Development",
    date: "2024-02-17",
    isFeatured: false,
  },
  {
    _id: "1",
    title: "How to Start a Tech Business",
    description: "A guide to launching your startup...",
    author: "John Doe",
    category: "Business",
    date: "2024-02-19",
    isFeatured: false,
  },
  {
    _id: "2",
    title: "Understanding AI in 2024",
    description: "Exploring the impact of AI...",
    author: "Jane Smith",
    category: "Technology",
    date: "2024-02-18",
    isFeatured: true,
  },
  {
    _id: "3",
    title: "Web Development Trends",
    description: "The latest trends in web development...",
    author: "Mike Johnson",
    category: "Web Development",
    date: "2024-02-17",
    isFeatured: false,
  },
  {
    _id: "1",
    title: "How to Start a Tech Business",
    description: "A guide to launching your startup...",
    author: "John Doe",
    category: "Business",
    date: "2024-02-19",
    isFeatured: false,
  },
  {
    _id: "2",
    title: "Understanding AI in 2024",
    description: "Exploring the impact of AI...",
    author: "Jane Smith",
    category: "Technology",
    date: "2024-02-18",
    isFeatured: true,
  },
  {
    _id: "3",
    title: "Web Development Trends",
    description: "The latest trends in web development...",
    author: "Mike Johnson",
    category: "Web Development",
    date: "2024-02-17",
    isFeatured: false,
  },
  {
    _id: "1",
    title: "How to Start a Tech Business",
    description: "A guide to launching your startup...",
    author: "John Doe",
    category: "Business",
    date: "2024-02-19",
    isFeatured: false,
  },
  {
    _id: "2",
    title: "Understanding AI in 2024",
    description: "Exploring the impact of AI...",
    author: "Jane Smith",
    category: "Technology",
    date: "2024-02-18",
    isFeatured: true,
  },
  {
    _id: "3",
    title: "Web Development Trends",
    description: "The latest trends in web development...",
    author: "Mike Johnson",
    category: "Web Development",
    date: "2024-02-17",
    isFeatured: false,
  },
  {
    _id: "1",
    title: "How to Start a Tech Business",
    description: "A guide to launching your startup...",
    author: "John Doe",
    category: "Business",
    date: "2024-02-19",
    isFeatured: false,
  },
  {
    _id: "2",
    title: "Understanding AI in 2024",
    description: "Exploring the impact of AI...",
    author: "Jane Smith",
    category: "Technology",
    date: "2024-02-18",
    isFeatured: true,
  },
  {
    _id: "3",
    title: "Web Development Trends",
    description: "The latest trends in web development...",
    author: "Mike Johnson",
    category: "Web Development",
    date: "2024-02-17",
    isFeatured: false,
  },
  {
    _id: "1",
    title: "How to Start a Tech Business",
    description: "A guide to launching your startup...",
    author: "John Doe",
    category: "Business",
    date: "2024-02-19",
    isFeatured: false,
  },
  {
    _id: "2",
    title: "Understanding AI in 2024",
    description: "Exploring the impact of AI...",
    author: "Jane Smith",
    category: "Technology",
    date: "2024-02-18",
    isFeatured: true,
  },
  {
    _id: "3",
    title: "Web Development Trends",
    description: "The latest trends in web development...",
    author: "Mike Johnson",
    category: "Web Development",
    date: "2024-02-17",
    isFeatured: false,
  },
  {
    _id: "1",
    title: "How to Start a Tech Business",
    description: "A guide to launching your startup...",
    author: "John Doe",
    category: "Business",
    date: "2024-02-19",
    isFeatured: false,
  },
  {
    _id: "2",
    title: "Understanding AI in 2024",
    description: "Exploring the impact of AI...",
    author: "Jane Smith",
    category: "Technology",
    date: "2024-02-18",
    isFeatured: true,
  },
  {
    _id: "3",
    title: "Web Development Trends",
    description: "The latest trends in web development...",
    author: "Mike Johnson",
    category: "Web Development",
    date: "2024-02-17",
    isFeatured: false,
  },
  {
    _id: "1",
    title: "How to Start a Tech Business",
    description: "A guide to launching your startup...",
    author: "John Doe",
    category: "Business",
    date: "2024-02-19",
    isFeatured: false,
  },
  {
    _id: "2",
    title: "Understanding AI in 2024",
    description: "Exploring the impact of AI...",
    author: "Jane Smith",
    category: "Technology",
    date: "2024-02-18",
    isFeatured: true,
  },
  {
    _id: "3",
    title: "Web Development Trends",
    description: "The latest trends in web development...",
    author: "Mike Johnson",
    category: "Web Development",
    date: "2024-02-17",
    isFeatured: false,
  },
  {
    _id: "1",
    title: "How to Start a Tech Business",
    description: "A guide to launching your startup...",
    author: "John Doe",
    category: "Business",
    date: "2024-02-19",
    isFeatured: false,
  },
  {
    _id: "2",
    title: "Understanding AI in 2024",
    description: "Exploring the impact of AI...",
    author: "Jane Smith",
    category: "Technology",
    date: "2024-02-18",
    isFeatured: true,
  },
  {
    _id: "3",
    title: "Web Development Trends",
    description: "The latest trends in web development...",
    author: "Mike Johnson",
    category: "Web Development",
    date: "2024-02-17",
    isFeatured: false,
  },
  {
    _id: "1",
    title: "How to Start a Tech Business",
    description: "A guide to launching your startup...",
    author: "John Doe",
    category: "Business",
    date: "2024-02-19",
    isFeatured: false,
  },
  {
    _id: "2",
    title: "Understanding AI in 2024",
    description: "Exploring the impact of AI...",
    author: "Jane Smith",
    category: "Technology",
    date: "2024-02-18",
    isFeatured: true,
  },
  {
    _id: "3",
    title: "Web Development Trends",
    description: "The latest trends in web development...",
    author: "Mike Johnson",
    category: "Web Development",
    date: "2024-02-17",
    isFeatured: false,
  },
  {
    _id: "1",
    title: "How to Start a Tech Business",
    description: "A guide to launching your startup...",
    author: "John Doe",
    category: "Business",
    date: "2024-02-19",
    isFeatured: false,
  },
  {
    _id: "2",
    title: "Understanding AI in 2024",
    description: "Exploring the impact of AI...",
    author: "Jane Smith",
    category: "Technology",
    date: "2024-02-18",
    isFeatured: true,
  },
  {
    _id: "3",
    title: "Web Development Trends",
    description: "The latest trends in web development...",
    author: "Mike Johnson",
    category: "Web Development",
    date: "2024-02-17",
    isFeatured: false,
  },
  {
    _id: "1",
    title: "How to Start a Tech Business",
    description: "A guide to launching your startup...",
    author: "John Doe",
    category: "Business",
    date: "2024-02-19",
    isFeatured: false,
  },
  {
    _id: "2",
    title: "Understanding AI in 2024",
    description: "Exploring the impact of AI...",
    author: "Jane Smith",
    category: "Technology",
    date: "2024-02-18",
    isFeatured: true,
  },
  {
    _id: "3",
    title: "Web Development Trends",
    description: "The latest trends in web development...",
    author: "Mike Johnson",
    category: "Web Development",
    date: "2024-02-17",
    isFeatured: false,
  },
];
